// Generated by CoffeeScript 1.3.3
(function() {

  define(['order!libs/jquery/jquery.min', 'order!libs/jquery/pubsub', 'order!libs/jquery/bootstrap.min'], function() {
    return $;
  });

}).call(this);
