// Generated by CoffeeScript 1.3.3
(function() {

  define(['Kendo', 'Glfx', 'mylibs/camera/camera', 'mylibs/bar/bottom', 'mylibs/bar/top', 'mylibs/popover/popover', 'mylibs/full/full', 'mylibs/postman/postman', 'mylibs/utils/utils', 'mylibs/gallery/gallery', 'mylibs/gallery/details', 'mylibs/events/events', 'mylibs/file/filewrapper', 'mylibs/about/about', 'mylibs/confirm/confirm', 'mylibs/assets/assets', 'mylibs/effects/effects', 'libs/record/record'], function(kendo, glfx, camera, bottom, top, popover, full, postman, utils, gallery, details, events, filewrapper, about, confirm, assets, effects, record) {
    var pub;
    return pub = {
      init: function() {
        var APP;
        APP = window.APP = {};
        APP.full = full;
        APP.filters = effects.data;
        APP.gallery = gallery;
        APP.about = about;
        APP.confirm = confirm;
        events.init();
        postman.init(window.top);
        assets.init();
        $.subscribe('/camera/unsupported', function() {
          return $('#pictures').append(intro);
        });
        $.publish("/postman/deliver", [true, "/menu/enable"]);
        $.subscribe("/localization/response", function(dict) {
          var ready;
          console.log(dict);
          ready = function() {
            APP.bottom = bottom.init(".bottom");
            APP.top = top.init(".top");
            APP.popover = popover.init("#gallery");
            full.init("#capture");
            details.init("#details");
            gallery.init("#thumbnails");
            about.init("#about");
            confirm.init("#confirm");
            effects.init();
            full.show(effects.data[0]);
            $.publish("/postman/deliver", [
              {
                message: ""
              }, "/app/ready"
            ]);
            return window.APP.app = new kendo.mobile.Application(document.body, {
              platform: "android"
            });
          };
          return camera.init("countdown", ready);
        });
        return $.publish("/postman/deliver", [null, "/localization/request"]);
      }
    };
  });

}).call(this);
