// Generated by CoffeeScript 1.3.3
(function() {

  require(['app', 'order!libs/jquery/plugins', 'order!libs/whammy/whammy.min', 'libs/webgl/glfx'], function(app) {
    return app.init();
  });

}).call(this);
