// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    paths: {
      Kendo: 'libs/kendo/kendo',
      Glfx: 'libs/glfx/glfx'
    }
  });

  require(['app', 'order!libs/jquery/plugins'], function(app) {
    return app.init();
  });

}).call(this);
