// Generated by CoffeeScript 1.3.3
(function() {

  define(['Kendo', 'text!mylibs/confirm/views/confirm.html'], function(kendo, template) {
    var open, pub, view,
      _this = this;
    view = {};
    this.callback = null;
    open = false;
    return pub = {
      yes: function(e) {
        view.data("kendoMobileModalView").close();
        open = false;
        if (_this.callback) {
          return _this.callback();
        }
      },
      no: function(e) {
        open = false;
        return view.data("kendoMobileModalView").close();
      },
      init: function(selector) {
        view = $(selector);
        $.subscribe("/confirm/show", function(title, message, callback) {
          _this.callback = callback;
          view.find(".title").html(title);
          view.find(".message").html(message);
          view.data("kendoMobileModalView").open();
          return open = true;
        });
        return $.subscribe("/keyboard/esc", function() {
          if (open) {
            return pub.no();
          }
        });
      }
    };
  });

}).call(this);
