// Generated by CoffeeScript 1.3.3
(function() {

  define(['Kendo', 'text!mylibs/about/views/about.html'], function(kendo, template) {
    var previous, pub, viewModel;
    previous = "#home";
    viewModel = kendo.observable({
      back: function() {
        $.publish("/postman/deliver", [true, "/menu/enable"]);
        return window.APP.app.navigate(previous);
      },
      gallery: {
        clear: function() {
          return $.publish("/confirm/show", [
            window.APP.localization.clear_gallery_dialog_title, window.APP.localization.clear_gallery_confirmation, function() {
              $.publish("/gallery/clear");
              return window.APP.app.navigate("#home");
            }
          ]);
        }
      }
    });
    return pub = {
      before: function() {
        return $.publish("/postman/deliver", [
          {
            paused: true
          }, "/camera/pause"
        ]);
      },
      hide: function() {
        $.publish("/postman/deliver", [
          {
            paused: false
          }, "/camera/pause"
        ]);
        return $.publish("/postman/deliver", [null, "/camera/request"]);
      },
      init: function(selector) {
        var view;
        view = new kendo.View(selector, template);
        view.render(viewModel, true);
        return $.subscribe('/menu/click/chrome-cam-about-menu', function() {
          $.publish("/postman/deliver", [false, "/menu/enable"]);
          previous = window.APP.app.view().id;
          return window.APP.app.navigate(selector);
        });
      }
    };
  });

}).call(this);
