// Generated by CoffeeScript 1.4.0
(function() {

  define(['Kendo', 'mylibs/navigation/navigation', 'text!mylibs/about/views/about.html'], function(kendo, navigation, template) {
    var click, previous, pub, viewModel;
    previous = "#home";
    viewModel = kendo.observable({});
    click = function(e) {
      return $.publish("/postman/deliver", [
        {
          link: e.target.href
        }, "/link/open"
      ]);
    };
    return pub = {
      before: function() {
        return $.publish("/postman/deliver", [
          {
            paused: true
          }, "/camera/pause"
        ]);
      },
      init: function(selector) {
        var view;
        view = new kendo.View(selector, template);
        view.render(viewModel, true);
        view.find("a").on("click", click);
        return $.subscribe('/menu/click/chrome-cam-about-menu', function() {
          $.publish("/postman/deliver", [false, "/menu/enable"]);
          previous = window.APP.app.view().id;
          return navigation.navigate(selector);
        });
      },
      back: function() {
        $.publish("/postman/deliver", [true, "/menu/enable"]);
        return navigation.navigate(previous);
      },
      clear: function() {
        return $.publish("/confirm/show", [
          window.APP.localization.clear_gallery_dialog_title, window.APP.localization.clear_gallery_confirmation, function() {
            $.publish("/gallery/clear");
            return navigation.navigate("#home");
          }
        ]);
      }
    };
  });

}).call(this);
