// Generated by CoffeeScript 1.3.3
(function() {

  define(['mylibs/utils/utils', 'libs/face/track'], function(utils, face) {
    /*     Camera
    
    The camera module takes care of getting the users media and drawing it to a canvas.
    It also handles the coutdown that is intitiated
    */

    var canvas, ctx, paused, pub, turnOn;
    canvas = {};
    ctx = {};
    paused = false;
    turnOn = function(callback, testing) {
      var track;
      track = {};
      $.subscribe("/camera/update", function(message) {
        var imgData, videoData;
        if (!paused) {
          imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
          videoData = new Uint8ClampedArray(message.image);
          imgData.data.set(videoData);
          ctx.putImageData(imgData, 0, 0);
          return $.publish("/camera/stream", [
            {
              canvas: canvas,
              track: message.track
            }
          ]);
        }
      });
      return callback();
    };
    return pub = {
      init: function(counter, callback) {
        canvas = document.createElement("canvas");
        canvas.width = 360;
        canvas.height = 240;
        ctx = canvas.getContext("2d");
        $.subscribe("/camera/pause", function(isPaused) {
          return paused = isPaused;
        });
        return turnOn(callback);
      }
    };
  });

}).call(this);
