// Generated by CoffeeScript 1.3.3
(function() {

  define(['mylibs/file/filewrapper'], function(filewrapper) {
    /*     Utils
    
    This file contains utility functions and normalizations. This used to contain more functions, but
    most have been moved into the extension.
    */

    var pub;
    return pub = {
      placeholder: {
        image: function() {
          return "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";
        }
      },
      oppositeDirectionOf: function(dir) {
        switch (dir) {
          case "left":
            return "right";
          case "right":
            return "left";
          case "up":
            return "down";
          case "down":
            return "up";
        }
      }
    };
  });

}).call(this);
