// Generated by CoffeeScript 1.3.3
(function() {

  define(['mylibs/file/filewrapper'], function(filewrapper) {
    /*     Utils
    
    This file contains utility functions and normalizations. this used to contain more functions, but
    most have been moved into the extension
    */

    var bufferCanvas, bufferContext, pub;
    bufferCanvas = document.createElement("canvas");
    bufferCanvas.width = 720 / 2;
    bufferCanvas.height = 480 / 2;
    bufferContext = bufferCanvas.getContext("2d");
    return pub = {
      getAnimationFrame: function() {
        return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback, element) {
          return window.setTimeout(callback, 1000 / 60);
        };
      },
      createVideo: function(frames) {
        var framesDone, i, transcode, _i, _ref;
        transcode = function() {
          var blob, blobUrl, i, name, pair, video, _i, _len, _ref;
          video = new Whammy.Video();
          _ref = (function() {
            var _j, _ref, _results;
            _results = [];
            for (i = _j = 0, _ref = frames.length - 2; 0 <= _ref ? _j <= _ref : _j >= _ref; i = 0 <= _ref ? ++_j : --_j) {
              _results.push(frames.slice(i, (i + 1) + 1 || 9e9));
            }
            return _results;
          })();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            pair = _ref[_i];
            video.add(pair[0].imageData, pair[1].time - pair[0].time);
          }
          blob = video.compile();
          frames = [];
          name = new Date().getTime() + ".webm";
          blobUrl = window.URL.createObjectURL(blob);
          console.log(blobUrl);
          filewrapper.save(name, blob);
          return $.publish("/bar/time/hide");
        };
        framesDone = 0;
        for (i = _i = 0, _ref = frames.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          bufferContext.putImageData(frames[i].imageData, 0, 0);
          frames[i] = {
            imageData: bufferCanvas.toDataURL('image/webp', 0.8),
            time: frames[i].time
          };
        }
        return transcode();
      }
    };
  });

}).call(this);
