// Generated by CoffeeScript 1.3.3
(function() {

  define(['mylibs/utils/utils'], function(utils) {
    var createTestFile, pub;
    createTestFile = function(fileName) {
      var file;
      return file = {
        fileName: fileName,
        thumbnailUrl: fileName,
        size: 128 * 1024,
        dateTaken: new Date()
      };
    };
    return pub = {
      init: function() {
        var data, i;
        data = (function() {
          var _i, _results;
          _results = [];
          for (i = _i = 1; _i <= 20; i = ++_i) {
            _results.push(createTestFile(i));
          }
          return _results;
        })();
        return this.dataSource = new kendo.data.DataSource({
          data: data,
          pageSize: 12
        });
      }
    };
  });

}).call(this);
