// Generated by CoffeeScript 1.3.3
(function() {

  define([], function(file) {
    var pub;
    return pub = {
      list: function() {
        var deferred, token;
        deferred = $.Deferred();
        token = $.subscribe("/file/listResult", function(result) {
          $.unsubscribe(token);
          return deferred.resolve(result.message);
        });
        $.publish("/postman/deliver", [{}, "/file/list", []]);
        return deferred.promise();
      },
      readAll: function() {
        var deferred, token;
        deferred = $.Deferred();
        token = $.subscribe("/pictures/bulk", function(result) {
          $.unsubscribe(token);
          return deferred.resolve(result.message);
        });
        $.publish("/postman/deliver", [{}, "/file/read", []]);
        return deferred.promise();
      },
      deleteFile: function(filename) {
        var deferred, token;
        deferred = $.Deferred();
        token = $.subscribe("/file/deleted/" + filename, function() {
          $.unsubscribe(token);
          return deferred.resolve();
        });
        $.publish("/postman/deliver", [
          {
            name: filename
          }, "/file/delete", []
        ]);
        return deferred.promise();
      },
      save: function(filename, blob) {
        var deferred, token;
        deferred = $.Deferred();
        token = $.subscribe("/file/saved/" + filename, function() {
          $.unsubscribe(token);
          return deferred.resolve();
        });
        $.publish("/postman/deliver", [
          {
            name: filename,
            file: blob
          }, "/file/save"
        ]);
        return deferred.promise();
      },
      readFile: function(filename) {
        throw "not implemented";
      }
    };
  });

}).call(this);
