// Generated by CoffeeScript 1.4.0
(function() {

  define([], function(file) {
    var asyncFileRequest, pub;
    asyncFileRequest = function(requestMessage, responseMessage, data) {
      var deferred, token;
      deferred = $.Deferred();
      token = $.subscribe(responseMessage, function(result) {
        $.unsubscribe(token);
        return deferred.resolve((result || {}).message);
      });
      $.publish("/postman/deliver", [data, requestMessage, []]);
      return deferred.promise();
    };
    return pub = window.filewrapper = {
      deleteFile: function(filename) {
        return asyncFileRequest("/file/delete", "/file/deleted/" + filename, {
          name: filename
        });
      },
      clear: function() {
        return asyncFileRequest("/file/clear", "/file/cleared", {});
      },
      save: function(filename, blob) {
        return asyncFileRequest("/file/save", "/file/saved/" + filename, {
          name: filename,
          file: blob
        });
      },
      fileListing: function() {
        return asyncFileRequest("/file/listing", "/file/listing/response", {});
      },
      readFile: function(file) {
        return asyncFileRequest("/file/read", "/file/read/" + file.name, {
          file: file.name
        });
      },
      readBulk: function(files) {
        var token;
        token = new Date().getTime();
        return asyncFileRequest("/file/bulk", "/file/bulk/" + token, {
          files: files,
          token: token
        });
      },
      download: function(file) {
        return $.publish("/postman/deliver", [
          {
            name: file.name
          }, "/file/download"
        ]);
      }
    };
  });

}).call(this);
