// Generated by CoffeeScript 1.4.0
(function() {

  define(['mylibs/utils/utils'], function(utils) {
    var pub;
    return pub = {
      init: function() {
        var p;
        p = function(name, key) {
          return $.publish("/keyboard/" + name, [key]);
        };
        return $(document).keydown(function(e) {
          switch (e.which) {
            case utils.keys.arrows.left:
              return p("arrow", "left");
            case utils.keys.arrows.right:
              return p("arrow", "right");
            case utils.keys.arrows.up:
              return p("arrow", "up");
            case utils.keys.arrows.down:
              return p("arrow", "down");
            case utils.keys.esc:
              return p("esc", "esc");
            case utils.keys.space:
              return p("space", {
                ctrlKey: e.ctrlKey || e.metaKey
              });
            case utils.keys.w:
              if (e.ctrlKey || e.metaKey) {
                return p("close");
              }
              break;
            case utils.keys.enter:
              return p("enter");
            case utils.keys.page.up:
              return p("page", "up");
            case utils.keys.page.down:
              return p("page", "down");
          }
        });
      }
    };
  });

}).call(this);
