// Generated by CoffeeScript 1.4.0
(function() {

  define(['mylibs/postman/postman', 'mylibs/utils/utils', 'mylibs/file/file', 'mylibs/localization/localization', 'libs/face/track', 'mylibs/effects/effects', 'mylibs/transfer/transfer'], function(postman, utils, file, localization, face, effects, transfer) {
    'use strict';

    var animate, canvas, capture, ctx, draw, effect, errback, flash, frame, hollaback, iframe, menu, paparazzi, paused, pub, supported, track, update, wrapper;
    iframe = iframe = document.getElementById("iframe");
    canvas = document.getElementById("canvas");
    ctx = canvas.getContext("2d");
    track = {
      faces: []
    };
    paused = false;
    wrapper = $(".wrapper");
    paparazzi = $(".paparazzi", wrapper);
    frame = 0;
    supported = true;
    effect = effects.data[0];
    window.cleanup = function() {
      video.pause();
      video.src = "";
      return stream.stop();
    };
    menu = function() {
      chrome.contextMenus.onClicked.addListener(function(info, tab) {
        return $.publish("/postman/deliver", [{}, "/menu/click/" + info.menuItemId]);
      });
      return $.subscribe("/menu/enable", function(isEnabled) {
        var menus, _i, _len, _results;
        menus = ["chrome-cam-about-menu"];
        _results = [];
        for (_i = 0, _len = menus.length; _i < _len; _i++) {
          menu = menus[_i];
          _results.push(chrome.contextMenus.update(menu, {
            enabled: isEnabled
          }));
        }
        return _results;
      });
    };
    draw = function() {
      update();
      return window.requestAnimationFrame(draw);
    };
    update = function() {
      if (paused) {
        return;
      }
      ctx.drawImage(video, canvas.width, 0, -canvas.width, canvas.height);
      if (effect.tracks && frame % 4 === 0) {
        track = face.track(canvas);
      }
      frame++;
      effects.advance(canvas);
      return effect.filter(canvas, canvas, frame, track);
    };
    capture = function(progress) {
      var flashCallback, image, name, saveFinished;
      if (progress.count > 1) {
        if (progress.index === 0) {
          paparazzi.removeClass("hidden");
        }
        if (progress.index === progress.count - 1) {
          setTimeout((function() {
            wrapper.removeClass("paparazzi-1");
            return paparazzi.addClass("hidden");
          }), 1000);
        }
        wrapper.removeClass("paparazzi-" + (1 + progress.count - progress.index));
        wrapper.addClass("paparazzi-" + (progress.count - progress.index));
      }
      image = canvas.toDataURL("image/jpeg", 1.0);
      name = new Date().getTime();
      file = {
        type: "jpg",
        name: "" + name + ".jpg",
        file: image
      };
      if (progress.index === 0) {
        transfer.setup();
      }
      flashCallback = function() {
        var callback;
        transfer.add(file, progress);
        callback = function() {
          return $.publish("/postman/deliver", [file, "/bottom/thumbnail"]);
        };
        if (progress.index === progress.count - 1) {
          return setTimeout((function() {
            return transfer.run(callback);
          }), 200);
        }
      };
      flash(flashCallback);
      $.publish("/file/save", [file]);
      saveFinished = $.subscribe("/file/saved/" + file.name, function() {
        $.unsubscribe(saveFinished);
        return $.publish("/postman/deliver", [file, "/captured/image"]);
      });
      return console.log(progress.index, progress.count);
    };
    flash = function(callback) {
      var anim, div, fx;
      div = $("#flash");
      fx = kendo.fx(div);
      return anim = fx.fadeIn().play().done(function() {
        return fx.fadeOut().play().done(function() {
          return callback();
        });
      });
    };
    animate = function(file, progress) {
      var callback;
      callback = function() {
        return $.publish("/postman/deliver", [file, "/bottom/thumbnail"]);
      };
      transfer.setup();
      transfer.add(file);
      return transfer.run(callback);
    };
    hollaback = function(stream) {
      var video;
      window.stream = stream;
      video = document.getElementById("video");
      video.src = window.URL.createObjectURL(stream);
      video.play();
      return window.requestAnimationFrame(draw);
    };
    errback = function() {
      return update = function() {
        paused = true;
        return $.publish("/postman/deliver", [{}, "/camera/unsupported"]);
      };
    };
    return pub = {
      init: function() {
        utils.init();
        transfer.init();
        $.subscribe("/camera/pause", function(message) {
          return paused = message.paused;
        });
        iframe.src = "app/index.html";
        postman.init(iframe.contentWindow);
        navigator.webkitGetUserMedia({
          video: true
        }, hollaback, errback);
        $.subscribe("/localization/request", function() {
          return $.publish("/postman/deliver", [localization, "/localization/response"]);
        });
        $.subscribe("/effects/request", function() {
          var e, filters;
          filters = (function() {
            var _i, _len, _ref, _results;
            _ref = effects.data;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              e = _ref[_i];
              _results.push({
                id: e.id,
                name: e.name
              });
            }
            return _results;
          })();
          return $.publish("/postman/deliver", [filters, "/effects/response"]);
        });
        $.subscribe("/effects/select", function(id) {
          var e, _i, _len, _ref, _results;
          _ref = effects.data;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            e = _ref[_i];
            if (e.id === id) {
              _results.push(effect = e);
            }
          }
          return _results;
        });
        $.subscribe("/window/close", function() {
          return window.close();
        });
        $.subscribe("/camera/capture", capture);
        $.subscribe("/camera/pause", function(message) {
          var image;
          wrapper.toggle(!message.paused);
          image = canvas.toDataURL("image/jpeg", 1.0);
          return $.publish("/postman/deliver", [image, "/camera/snapshot"]);
        });
        file.init();
        face.init(0, 0, 0, 0);
        menu();
        return $(iframe).focus();
      }
    };
  });

}).call(this);
