// Generated by CoffeeScript 1.3.3
(function() {

  require(['order!libs/jquery/jquery', 'order!libs/whammy/whammy.min', 'app'], function($, whammy, app) {
    return app.init();
  });

}).call(this);
