// Generated by CoffeeScript 1.4.0
(function() {

  define(['order!libs/kendo/kendo.view', 'order!libs/kendo/kendo.mobile.clickable', 'order!libs/kendo/kendo.custom.binders'], function() {
    return kendo;
  });

}).call(this);
