// Generated by CoffeeScript 1.3.3
(function() {

  define(['order!libs/kendo/kendo.core', 'order!libs/kendo/kendo.fx', 'order!libs/kendo/kendo.data', 'order!libs/kendo/kendo.binder', 'order!libs/kendo/kendo.userevents', 'order!libs/kendo/kendo.touch'], function() {
    return kendo;
  });

}).call(this);
