// Generated by CoffeeScript 1.3.3
(function() {

  define(['order!libs/kendo/kendo.core', 'order!libs/kendo/kendo.fx', 'order!libs/kendo/kendo.data', 'order!libs/kendo/kendo.binder', 'order!libs/kendo/kendo.history', 'order!libs/kendo/kendo.draganddrop', 'order!libs/kendo/kendo.mobile.scroller', 'order!libs/kendo/kendo.mobile.view', 'order!libs/kendo/kendo.mobile.loader', 'order!libs/kendo/kendo.mobile.pane', 'order!libs/kendo/kendo.mobile.application', 'order!libs/kendo/kendo.userevents', 'order!libs/kendo/kendo.touch'], function() {
    return kendo;
  });

}).call(this);
