// Generated by CoffeeScript 1.3.3
(function() {

  define(['text!mylibs/bar/views/bar.html'], function(template) {
    var pub;
    return pub = {
      init: function(selector) {
        var $container, $content;
        $container = $(selector);
        $content = $(template);
        $content.click(function() {
          return $.publish("/capture/image");
        });
        $content.find(".show-gallery").toggle((function() {
          return $.publish("/gallery/list");
        }), (function() {
          return $.publish("/gallery/hide");
        }));
        return $container.append($content);
      }
    };
  });

}).call(this);
