// Generated by CoffeeScript 1.4.0
(function() {

  define(['Kendo', 'mylibs/navigation/navigation', 'mylibs/file/filewrapper', 'text!mylibs/bar/views/top.html'], function(kendo, navigation, filewrapper, template) {
    var pub, states, viewModel,
      _this = this;
    viewModel = kendo.observable({
      current: null,
      selected: false,
      back: {
        details: false,
        text: "< Camera"
      }
    });
    states = {
      selected: function() {
        return viewModel.set("selected", true);
      },
      deselected: function() {
        return viewModel.set("selected", false);
      },
      details: function() {
        viewModel.set("back.text", "< Gallery");
        viewModel.set("back.details", true);
        return $.publish("/gallery/details", [true]);
      },
      gallery: function() {
        viewModel.set("back.text", "< Camera");
        viewModel.set("back.details", false);
        return $.publish("/gallery/details", [false]);
      },
      set: function(state) {
        states.current = state;
        return states[state]();
      }
    };
    return pub = {
      init: function(container) {
        var back, view;
        view = new kendo.View(container, template);
        view.render(viewModel, true);
        back = view.find(".back.button");
        $.subscribe("/top/update", function(state) {
          return states.set(state);
        });
        $.subscribe("/item/selected", function(message) {
          return viewModel.set("current", message.item);
        });
        return $.subscribe("/keyboard/esc", function() {
          if (states.current === "details") {
            states.set("gallery");
            return back.trigger("click");
          }
        });
      },
      back: function(e) {
        $.publish("/details/hide");
        states.gallery();
        return e.preventDefault();
      },
      destroy: function(e) {
        var view;
        view = viewModel.get("back.details") ? "details" : "gallery";
        $.publish("/" + view + "/keyboard", [false]);
        return $.publish("/confirm/show", [
          window.APP.localization.delete_dialog_title, window.APP.localization.delete_confirmation, function(destroy) {
            $.publish("/" + view + "/keyboard", [true]);
            if (destroy) {
              return $.publish("/gallery/delete");
            }
          }
        ]);
      },
      save: function(e) {
        return filewrapper.download(viewModel.get("current"));
      },
      home: function(e) {
        return navigation.navigate("#home");
      }
    };
  });

}).call(this);
