// Generated by CoffeeScript 1.4.0
(function() {

  define(['mylibs/utils/utils'], function(utils) {
    var keydown, level, pub, removeTabindices, setLevel;
    level = 0;
    keydown = function(e) {
      var target;
      if (!(e.which === utils.keys.space || e.which === utils.keys.enter)) {
        return;
      }
      target = $(e.target);
      if (target.data("role") === "button") {
        return target.data("kendoMobileButton").trigger("click", e);
      } else if (target.data("role") === "clickable") {
        return target.data("kendoMobileClickable").trigger("click", e);
      }
    };
    removeTabindices = function() {
      return $("[data-tabbable]").attr("tabindex", -1);
    };
    setLevel = function(level) {
      this.level = level;
      removeTabindices();
      return setTimeout((function() {
        $("[data-tab-level='" + level + "']").attr("tabindex", 0);
        return $("[data-tab-level='" + level + "'][data-default-action]").focus();
      }), 400);
    };
    return pub = {
      init: function() {
        $(document.body).on("keydown", "[data-tabbable]", keydown);
        $.subscribe("/tabbing/level/set", setLevel);
        return $.subscribe("/tabbing/refresh", function() {
          return $("[data-tab-level='" + level + "']").attr("tabindex", 0);
        });
      }
    };
  });

}).call(this);
