// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var key, keys, pub, _i, _len;
    pub = {};
    keys = ["appName", "appDesc", "aboutMenuItem", "clearGalleryButton", "clearGalleryConfirmation", "filtersButton", "backButton", "backToCameraButton", "saveButton", "deleteDialogTitle", "deleteConfirmation", "yesButton", "noButton", "normal", "andy", "blockhead", "blueberry", "bulge", "colorHalfTone", "chubbyBunny", "dent", "flush", "frogman", "ghost", "giraffe", "inverted", "kaleidoscope", "mirrorLeft", "oldFilm", "photocopy", "pinch", "pixelate", "quad", "reflection", "sepia", "swirl", "zoomBlur"];
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      pub[key] = chrome.i18n.getMessage(key);
    }
    return pub;
  });

}).call(this);
