// Generated by CoffeeScript 1.4.0
(function() {

  define(['libs/face/track', 'mylibs/effects/effects', 'mylibs/transfer/transfer'], function(face, effects, transfer) {
    'use strict';

    var animate, canvas, capture, ctx, draw, effect, errback, flash, frame, hollaback, paparazzi, pause, paused, pub, supported, track, update, video, wrapper;
    canvas = document.getElementById("canvas");
    ctx = canvas.getContext("2d");
    track = {
      faces: []
    };
    video = null;
    paused = false;
    wrapper = $(".wrapper");
    paparazzi = $(".paparazzi", wrapper);
    frame = 0;
    supported = true;
    effect = effects.data[0];
    draw = function() {
      update();
      return window.requestAnimationFrame(draw);
    };
    update = function() {
      if (paused) {
        return;
      }
      ctx.drawImage(video, canvas.width, 0, -canvas.width, canvas.height);
      if (effect.tracks && frame % 4 === 0) {
        track = face.track(canvas);
      }
      frame++;
      effects.advance(canvas);
      return effect.filter(canvas, canvas, frame, track);
    };
    capture = function(progress) {
      var file, image, name, saveFinished;
      flash();
      if (progress.count > 1) {
        if (progress.index === 0) {
          paparazzi.removeClass("hidden");
        }
        if (progress.index === progress.count - 1) {
          setTimeout((function() {
            wrapper.removeClass("paparazzi-1");
            return paparazzi.addClass("hidden");
          }), 1000);
        }
        wrapper.removeClass("paparazzi-" + (1 + progress.count - progress.index));
        wrapper.addClass("paparazzi-" + (progress.count - progress.index));
      }
      image = canvas.toDataURL("image/jpeg", 1.0);
      name = new Date().getTime();
      file = {
        type: "jpg",
        name: "" + name + ".jpg",
        file: image
      };
      $.publish("/file/save", [file]);
      saveFinished = $.subscribe("/file/saved/" + file.name, function() {
        $.unsubscribe(saveFinished);
        return $.publish("/postman/deliver", [file, "/captured/image"]);
      });
      return animate(file);
    };
    flash = function() {
      var anim, div, fx;
      div = $("#flash");
      fx = kendo.fx(div);
      return anim = fx.fadeIn().play().done(function() {
        return fx.fadeOut().play();
      });
    };
    animate = function(file) {
      var callback;
      callback = function() {
        return $.publish("/postman/deliver", [file, "/bottom/thumbnail"]);
      };
      transfer.setup();
      transfer.add(file);
      return transfer.run(callback);
    };
    hollaback = function(stream) {
      window.stream = stream;
      video = document.getElementById("video");
      video.src = window.URL.createObjectURL(stream);
      video.play();
      return window.requestAnimationFrame(draw);
    };
    errback = function() {
      return update = function() {
        wrapper.hide();
        paused = true;
        return $.publish("/postman/deliver", [{}, "/camera/unsupported"]);
      };
    };
    pause = function(message) {
      var image;
      paused = message.paused;
      wrapper.toggle(!paused);
      image = canvas.toDataURL("image/jpeg", 1.0);
      return $.publish("/postman/deliver", [image, "/camera/snapshot"]);
    };
    return pub = {
      cleanup: function() {
        video.pause();
        video.src = "";
        return stream.stop();
      },
      init: function() {
        transfer.init();
        navigator.webkitGetUserMedia({
          video: true
        }, hollaback, errback);
        $.subscribe("/camera/capture", capture);
        $.subscribe("/camera/pause", pause);
        $.subscribe("/effects/request", function() {
          var e, filters;
          filters = (function() {
            var _i, _len, _ref, _results;
            _ref = effects.data;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              e = _ref[_i];
              _results.push({
                id: e.id,
                name: e.name
              });
            }
            return _results;
          })();
          return $.publish("/postman/deliver", [filters, "/effects/response"]);
        });
        $.subscribe("/camera/effect", function(id) {
          var e, _i, _len, _ref, _results;
          _ref = effects.data;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            e = _ref[_i];
            if (e.id === id) {
              _results.push(effect = e);
            }
          }
          return _results;
        });
        return face.init(0, 0, 0, 0);
      }
    };
  });

}).call(this);
